import { Providers } from './providers'
import { ReactNode } from 'react'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-br">
      <head />
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}

